export const PROTOCOLS = {
  AUDITORIA: "AUDITORIA",
  SEO_OPTIMIZATION: "SEO_OPTIMIZATION",
  CRO_OPTIMIZATION: "CRO_OPTIMIZATION",
  SEM_AUTOMATION: "SEM_AUTOMATION",
  ECOMMERCE_GROWTH: "ECOMMERCE_GROWTH",
  DIGITAL_TRANSFORMATION: "DIGITAL_TRANSFORMATION",
} as const;

